---
sidebar: sidebar 
permalink: task-quick-start.html 
keywords: quick start, set up cloud volumes service 
summary: 'Pour commencer rapidement, suivez ces étapes ou suivez les liens ci-dessous pour obtenir plus d"informations.' 
---
= Démarrage rapide de Cloud Volumes Service pour Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Pour commencer rapidement, suivez ces étapes ou suivez les liens ci-dessous pour obtenir plus d'informations.

[role="quick-margin-para"]
Depuis Google, activez l'API Cloud Volumes Service pour GCP afin que BlueXP puisse gérer les abonnements et les volumes cloud.

[role="quick-margin-para"]
link:task-set-up-google-cloud.html["Découvrez comment activer l'API"].

[role="quick-margin-para"]
Depuis Google, créez un compte de service et un rôle afin que BlueXP puisse accéder à votre compte Cloud Volumes Service pour Google Cloud.

[role="quick-margin-para"]
link:task-set-up-google-cloud.html#set-up-a-service-account["Découvrez comment configurer un compte de service"].

[role="quick-margin-para"]
Dans BlueXP, cliquez sur *Ajouter un environnement de travail* > *Google Cloud* > *Cloud Volumes Service*, puis fournissez des détails sur le compte de service et le projet Google Cloud.

[role="quick-margin-para"]
link:task-create-working-env.html["Découvrez comment créer un environnement de travail"].
